import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
        <div className="fixed inset-0 pointer-events-none flex justify-center items-center opacity-10 z-0">
          <h1 className="text-8xl font-bold text-gray-500 select-none">
            Mr.Damager
          </h1>
        </div>
      </body>
    </html>
  );
}
